### PR TITLE
Merge codes

### PR DESCRIPTION
**Pull request by langtuqn2007**
Merge codes

### CODE REVIEW

**Comment by eujun** [comment]
I still don't know how to merge my part with yours but here is mine. I did
the users page for localhost/users but I'm not sure about
localhost/post/users, are they suppose to be the same or different? Admin
can now ban, unban, delete users. Also added a check to make sure admin
cannot delete self
https://github.com/eujun/CIS526-Srping2016

**Comment by eujun** [comment]
oh and let me know when you want to start using discord

**Comment by langtuqn2007** [comment]
localhost/users and localhost/post/users should be the same. However, as I
said before, I merged from two codes so the implementation can be
different. I think at default it should be localhost/post/users, but if you
wanna change the whole thing to localhost/users, I don't see any problem
with it.

Oh and send me the discord link.

**Comment by langtuqn2007** [comment]
About the discord, here is the link to my server:
https://discord.gg/0zdL4ymXTRYUiz7j

**Pull request merged**
